DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS whistles;

DROP TABLE IF EXISTS party_affiliations;

DROP TABLE IF EXISTS parties;

DROP TABLE IF EXISTS votes;

DROP TABLE IF EXISTS polls;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS vote_type;