-- psql -U postgres -h 127.0.0.1 -d liquid_democracy -f .../liquid-democracy/database/populate.sql
INSERT INTO
  users (name, password, password_salt)
VALUES
  ('Alice', 'dc90cf07de907ccc64636ceddb38e552a1a0d984743b1f36a447b73877012c39', 'salt1'),
  ('Bob', 'dbc4579ae2b3ab293213f42bb852706ea995c3b5c3987f8aa9faae5004acb3cf', 'salt2'),
  ('Charlie', 'password3', 'salt3'),
  ('Dave', 'password4', 'salt4'),
  ('Eve', 'password5', 'salt5'),
  ('Frank', 'password6', 'salt6'),
  ('Grace', 'password7', 'salt7'),
  ('Heidi', 'password8', 'salt8'),
  ('Ivan', 'password9', 'salt9'),
  ('Judy', 'password10', 'salt10'),
  ('Karen', 'password11', 'salt11'),
  ('Liam', 'password12', 'salt12'),
  ('Mia', 'password13', 'salt13'),
  ('Noah', 'password14', 'salt14'),
  ('Olivia', 'password15', 'salt15'),
  ('Penelope', 'password16', 'salt16'),
  ('Quinn', 'password17', 'salt17'),
  ('Riley', 'password18', 'salt18'),
  ('Samantha', 'password19', 'salt19'),
  ('Thomas', 'password20', 'salt20'),
  ('Uma', 'password21', 'salt21'),
  ('Violet', 'password22', 'salt22'),
  ('William', 'password23', 'salt23'),
  ('Xander', 'password24', 'salt24'),
  ('Yara', 'password25', 'salt25'),
  ('Zachary', 'password26', 'salt26'),
  ('Abby', 'password27', 'salt27'),
  ('Benjamin', 'password28', 'salt28'),
  ('Caleb', 'password29', 'salt29'),
  ('Daisy', 'password30', 'salt30'),
  ('Ella', 'password31', 'salt31'),
  ('Finn', 'password32', 'salt32'),
  ('Greta', 'password33', 'salt33'),
  ('Henry', 'password34', 'salt34'),
  ('Isabella', 'password35', 'salt35'),
  ('Jack', 'password36', 'salt36'),
  ('Katie', 'password37', 'salt37'),
  ('Leo', 'password38', 'salt38'),
  ('Maggie', 'password39', 'salt39'),
  ('Nate', 'password40', 'salt40'),
  ('Oliver', 'password41', 'salt41'),
  ('Piper', 'password42', 'salt42'),
  ('Quincy', 'password43', 'salt43'),
  ('Ruby', 'password44', 'salt44'),
  ('Sam', 'password45', 'salt45'),
  ('Tessa', 'password46', 'salt46'),
  ('Ulysses', 'password47', 'salt47'),
  ('Vivian', 'password48', 'salt48'),
  ('Wyatt', 'password49', 'salt49'),
  ('Ximena', 'password50', 'salt50');

INSERT INTO
  polls (name, description, start, end)
VALUES
  ('Do you like dogs?', 'This poll is about your affinity towards dogs.', NOW() - INTERVAL 1 MONTH, NOW() - INTERVAL 2 WEEK),
  ('Do you prefer summer over winter?', 'This poll is about your preference between summer and winter.', NOW() - INTERVAL 2 WEEK, NOW() + INTERVAL 2 WEEK),
  ('Do you like spicy food?', 'This poll is about your taste for spicy food.', NOW() + INTERVAL 2 WEEK, NOW() + INTERVAL 1 MONTH),
  ('Do you enjoy playing video games?', 'This poll is about your interest in playing video games.', NOW() + INTERVAL 1 MONTH, NOW() + INTERVAL 2 MONTH),
  ('Do you like to travel?', 'This poll is about your interest in traveling.', NOW() + INTERVAL 2 MONTH, NOW() + INTERVAL 3 MONTH),
  ('Do you prefer coffee over tea?', 'This poll is about your preference between coffee and tea.', NOW() + INTERVAL 3 MONTH, NOW() + INTERVAL 4 MONTH),
  ('Do you like to read books?', 'This poll is about your interest in reading books.', NOW() + INTERVAL 4 MONTH, NOW() + INTERVAL 5 MONTH),
  ('Do you enjoy watching movies?', 'This poll is about your interest in watching movies.', NOW() + INTERVAL 5 MONTH, NOW() + INTERVAL 6 MONTH),
  ('Do you like to cook?', 'This poll is about your interest in cooking.', NOW() + INTERVAL 6 MONTH, NOW() + INTERVAL 7 MONTH),
  ('Do you prefer the beach over the mountains?', 'This poll is about your preference between the beach and the mountains.', NOW() + INTERVAL 7 MONTH, NOW() + INTERVAL 8 MONTH),
  ('Do you like to exercise?', 'This poll is about your interest in exercising.', NOW() + INTERVAL 8 MONTH, NOW() + INTERVAL 9 MONTH),
  ('Do you enjoy listening to music?', 'This poll is about your interest in listening to music.', NOW() + INTERVAL 9 MONTH, NOW() + INTERVAL 10 MONTH),
  ('Do you like to dance?', 'This poll is about your interest in dancing.', NOW() + INTERVAL 10 MONTH, NOW() + INTERVAL 11 MONTH),
  ('Do you prefer sweet over savory food?', 'This poll is about your preference between sweet and savory food.', NOW() + INTERVAL 11 MONTH, NOW() + INTERVAL 12 MONTH),
  ('Do you like to play sports?', 'This poll is about your interest in playing sports.', NOW() + INTERVAL 12 MONTH, NOW() + INTERVAL 13 MONTH),
  ('Do you enjoy going to concerts?', 'This poll is about your interest in going to concerts.', NOW() + INTERVAL 13 MONTH, NOW() + INTERVAL 14 MONTH),
  ('Do you like to paint or draw?', 'This poll is about your interest in painting or drawing.', NOW() + INTERVAL 14 MONTH, NOW() + INTERVAL 15 MONTH),
  ('Do you prefer the city over the countryside?', 'This poll is about your preference between the city and the countryside.', NOW() + INTERVAL 15 MONTH, NOW() + INTERVAL 16 MONTH),
  ('Do you like to sing?', 'This poll is about your interest in singing.', NOW() + INTERVAL 16 MONTH, NOW() + INTERVAL 17 MONTH),
  ('Do you enjoy going to the theater?', 'This poll is about your interest in going to the theater.', NOW() + INTERVAL 17 MONTH, NOW() + INTERVAL 18 MONTH);

INSERT INTO
  parties (name, color)
VALUES
  ('Nice Party', 'red'),
  ('Super Party', 'blue'),
  ('Awesome Party', 'green'),
  ('Cool Party', 'yellow'),
  ('Great Party', 'purple');

